### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by crackytsi** [3c7/aptmap#4]
Hi,
Sorry for such a beginner question, but can you provide an (short) installation guide?
I don't understand which components needs to be installed / configured.
Assume that the ts files in src directory belongs to angular, but I don't get the Connection to the public JavaScript and Website.

thanks a lot

**Comment by 3c7** [comment]
Hey @crackytsi,
you can install it using the node package manager npm. The process in general would be:

- Clone repo
- Clone submodules: `git submodule update --init`
- Install node.js dependencies: `npm install`
- Run or package the scripts `npm run serve`/`npm run build`

It's not based on angular, but on vue.js and typescript. I want to refactor it and use pure JS in the future. Hope I could help you.

**Comment by 3c7** [comment]
BTW. this map uses not the newest version of the galaxy, because in the newest version there are some `meta` key's missing and I did not implement catching missing keys in the source code. :innocent:

**Comment by 3c7** [comment]
(Addition: netlify uses this repo and produces the webpage with `npm run build`)

**Comment by josepharius** [comment]
Hi, I am a beginner in infosec with my colleague and she referred me to this map. I have an Ubuntu VM running XAMPP. Can I host this app locally?

**Comment by 3c7** [comment]
Hey @josepharius, yes you can run that app locally. In order to build it you need nodejs.

- Clone the repo
- `npm install` it
- Build it using `npm run build`
- Change into `dist` directory
- Serve it via any http server, e.g. `python3 -mhttp.server --bind 127.0.0.1`
- Visit http://127.0.0.1:8000

**Comment by josepharius** [comment]
Hello sorry to bother again,

I have cloned the repo and was able to run npm install, albeit with some warnings.

However, I get this when I run npm run build in the folder:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle aptmap@0.1.9~prebuild: aptmap@0.1.9
6 silly lifecycle aptmap@0.1.9~prebuild: no script for prebuild, continuing
7 info lifecycle aptmap@0.1.9~build: aptmap@0.1.9
8 verbose lifecycle aptmap@0.1.9~build: unsafe-perm in lifecycle true
9 verbose lifecycle aptmap@0.1.9~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/anyhowdo/aptmap/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle aptmap@0.1.9~build: CWD: /home/anyhowdo/aptmap
11 silly lifecycle aptmap@0.1.9~build: Args: [ '-c',
11 silly lifecycle   'git submodule update --remote --init && ./update-actors.py && vue-cli-service build' ]
12 info lifecycle aptmap@0.1.9~build: Failed to exec build script
13 verbose stack Error: aptmap@0.1.9 build: `git submodule update --remote --init && ./update-actors.py && vue-cli-service build`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid aptmap@0.1.9
15 verbose cwd /home/anyhowdo/aptmap
16 error Linux 4.18.0-18-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error aptmap@0.1.9 build: `git submodule update --remote --init && ./update-actors.py && vue-cli-service build`
24 error spawn ENOENT
25 error Failed at the aptmap@0.1.9 build script 'git submodule update --remote --init && ./update-actors.py && vue-cli-service build'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the aptmap package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     git submodule update --remote --init && ./update-actors.py && vue-cli-service build
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs aptmap
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls aptmap
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

Did I do anything wrong?

**Comment by 3c7** [comment]
No, you didn't do anything wrong. I forgot to mention the python script that updates the threat actor json object. It might uses modules you haven't installed right now. Best would be to create a virtual environment and install the necessary dependencies:
```bash
python3 -mvenv venv
source venv/bin/activate
pip install -r requirements.txt
npm run build
```

**Comment by 3c7** [comment]
Also, if you're running XAMPP, you can copy the content of the resulting `dist` directory to your www-root to serve it via XAMPP.

**Comment by josepharius** [comment]
Thank you for your help! I was able to build it. The issue was resolved due to http://www.kean.ph/how-to-fix-usrbinenv-python3r-no-such-file-or-directory/.

After resolving it, I was able to build but the layout was off.

Once I have resolved all the issues, I would like to contribute a short installation guide if that is ok with you.

Thank you again!

**Comment by 3c7** [comment]
You're of course welcome to contribute an installation guide, but to be honest, this project is not actively maintained.

**Comment by josepharius** [comment]
Can I make the display style same as the one in Netlify?

![Untitled](https://user-images.githubusercontent.com/49582994/57610524-8d2a7600-75a3-11e9-816e-88e17e7c9055.png)

**Comment by 3c7** [comment]
It should be the same display style. Your server seems to miss the bootstrap css files. There should be HTTP 404 errors in your web console.
